apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-nginx-config
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        access_log /dev/stdout;
        error_log /dev/stderr;

        location /health {
            return 200 'ok';
            add_header Content-Type text/plain;
        }

        location /api/incidencies/ {
            proxy_pass http://product-service:5000/incidencies/;
        }

        location /api/tasques/ {
            proxy_pass http://order-service:5001/tasques/;
        }

        location /api/usuaris/ {
            proxy_pass http://user-service:5002/usuaris/;
        }

        location / {
            return 200 "Resposta des de api-gateway\n";
            add_header Content-Type text/plain;
        }
    }
