apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.cache.replicas }}
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: redis
          image: "{{ .Values.cache.image.repository }}:{{ .Values.cache.image.tag }}"
          imagePullPolicy: {{ .Values.cache.image.pullPolicy }}
          ports:
            - containerPort: 6379
