apiVersion: v1
kind: Secret
metadata:
  name: db-orders-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.dbOrders.auth.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.dbOrders.auth.database | quote }}
