apiVersion: v1
kind: Service
metadata:
  name: db-orders-headless
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: db-orders
  ports:
    - port: 3306
      targetPort: 3306
