apiVersion: v1
kind: Secret
metadata:
  name: db-products-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.dbProducts.auth.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.dbProducts.auth.database | quote }}
