apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.4
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: root_password
            - name: MARIADB_DATABASE
              value: appdb
          ports:
            - containerPort: 3306
