server {
    listen 80;
    server_name _;

    access_log /dev/stdout;
    error_log /dev/stderr;

    resolver 127.0.0.11 ipv6=off valid=10s;

    # CORS (IMPORTANT)
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Content-Type" always;

    if ($request_method = OPTIONS) {
        return 204;
    }

    location / {
        return 200 "Resposta des de api-gateway\n";
        add_header Content-Type text/plain;
    }

    location /api/incidencies/ {
        proxy_pass http://product-service:5000/incidencies/;
    }

    location /api/tasques/ {
        proxy_pass http://order-service:5001/tasques/;
    }

    location /api/usuaris/ {
        proxy_pass http://user-service:5002/usuaris/;
    }

    location /health {
        return 200 "ok";
        add_header Content-Type text/plain;
    }
}
